name: sample_mvvm_with_bloc
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_svg: ^2.0.7

  auto_route: ^9.2.2
  google_fonts: ^6.0.0
  freezed: ^2.4.5

  flutter_bloc: ^8.1.3
  logger: ^2.0.2
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  url_launcher: ^6.1.14
  dio: ^5.3.3
  retrofit: ^4.0.1
  json_annotation: ^4.9.0

  jwt_decoder: ^2.0.1

  shimmer: ^3.0.0

  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  file_picker:
  intl:
#  utils
  dotted_border: ^2.1.0
  dropdown_button2:
  flutter_smart_dialog: ^4.9.0+4
  form_validator:
  connectivity_plus: ^6.1.1
  fluttertoast:

dependency_overrides:
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

  auto_route_generator: ^9.0.0
  build_runner:
  retrofit_generator: ^9.1.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

